- name: Install prerequisites
  apt: name={{item}} state=present update_cache=yes install_recommends=False
  with_items: [ apt-transport-https, ca-certificates, software-properties-common ]
- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg
- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
- name: Install Docker
  apt: name='docker-ce=17.03*' state=present update_cache=yes install_recommends=False
