- name: download rke
  get_url: url={{ rke_url }} dest=/tmp/rke mode=a+x
- name: generate ssh key on first controller
  command: ssh-keygen -t rsa -f /root/.ssh/id_rsa -N ''
  args:
    creates: /root/.ssh/id_rsa
- name: generate ssh public key
  command: ssh-keygen -y -f /root/.ssh/id_rsa
  register: ssh_keygen_public
- name: install ssh key to all servers
  authorized_key: user=root key={{ ssh_keygen_public.stdout }}
  delegate_to: "{{ item }}"
  with_items:
  - "{{ groups['g_controllers'] | union(groups['g_workers']) }}"
- name: install pip
  apt:  name=python-pip state=present update_cache=yes install_recommends=False
- name: install pyOpenSSL for certificate generation
  pip: name=pyOpenSSL
- name: create directory for CA key
  file: path=/root/CA mode=0700 state=directory
- name: generate certificates
  block:
  - name: generate CA key
    openssl_privatekey:
      path: /root/CA/key
  - name: generate CA CSR
    openssl_csr:
      path: /root/CA/csr
      common_name: cattle
      privatekey_path: /root/CA/key
  - name: create CA certificate
    openssl_certificate:
      path: /root/CA/cert
      privatekey_path: /root/CA/key
      csr_path: /root/CA/csr
      provider: selfsigned
      # valid for 10 years
      valid_in: 315360000
